### ISSUE TITLE
Please for the love of the prediction community

### ISSUE THREAD

**Issue by SamuelLachance** [NeilPaine538/NHL_GAR_data#1]
Many of us use your nhl_gar_historical.csv for making our predictions .

please can you keep it updated  ? 

god bless you

**Comment by Neil-Paine-1** [comment]
Hi! Yes, that's the plan, probably once every team has played at least 1 game.

**Comment by Neil-Paine-1** [comment]
@SamuelLachance This is now updating: https://github.com/Neil-Paine-1/NHL-Player-And-Team-Ratings/blob/master/nhl_gar_historical.csv

**Comment by SamuelLachance** [comment]
you are the goat

**Comment by SamuelLachance** [comment]
ty
